### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/movies#85]
Choose and setup localization app.

## todo

- [x] load `en.json` https://github.com/krsiakdaniel/movies/pull/97
- [x] connect POEditor
- [x] test https://github.com/krsiakdaniel/movies/commit/184f97a3a44561a9366fbecea0063f9d879ba2ac
- [x] connect GitLocalize [repo: 4460](https://gitlocalize.com/repo/4460)
- [x] test https://github.com/krsiakdaniel/movies/commit/11ac85c93bbd749a04715170b94eba5204f15010 + https://github.com/krsiakdaniel/movies/commit/ed9ae90ce0570d0f2e5eab67bbfa856040385d85
- [x] CHOOSE ONE

> POEditor is better
